---
format: 
  pdf:
    documentclass: article
    classoption: letterpaper
    fontsize: 9pt
    header-includes:
      - \usepackage{fontspec}
      - \setmainfont{Arial}
      - \usepackage{geometry}
      - \geometry{top=0.4in, bottom=0.4in, left=0.4in, right=0.4in}
      - \usepackage{setspace}
      - \setstretch{0.8}
      - \usepackage{fancyhdr}
      - \pagestyle{fancy}
      - \fancyfoot{}
      - \renewcommand{\headrulewidth}{0pt}
      - \renewcommand{\footrulewidth}{0pt}
  html: default
  md: default

comment: |
  This file is my data-driven resume.  It can be used for generating PDF, Markdown and HTML versions of the resume.
  To render all formats of all Quarto files (.qmd), the command is `quarto render *.qmd`.
  To render only a certain format, say PDF, the command is `quarto render *.qmd --to pdf`.
---

```{r setup, include=FALSE}
library(lubridate)
start_date <- ymd("2023-06-19")
end_date <- today()
time_diff <- interval(start_date, end_date)
years <- as.period(time_diff)@year
months <- as.period(time_diff)@month
time_lapsed_str <- ifelse(years > 0 & months > 0,
                          paste0(years, " year", ifelse(years != 1, "s", ""), " and ", months, " month", ifelse(months != 1, "s", "")),
                          ifelse(years > 0,
                                 paste0(years, " year", ifelse(years != 1, "s", "")),
                                 paste0(months, " month", ifelse(months != 1, "s", ""))))
```

# STEVEN LEUNG, Master of Data Science, PMP
-   [steven.leung\@alumni.ucla.edu](mailto:steven.leung@alumni.ucla.edu), Mobile: 604-499-3173, [LinkedIn](https://www.linkedin.com/in/stevenleung08), [GitHub](https://stevenleung2018.github.io)

## PROFESSIONAL SUMMARY

-   `r time_lapsed_str` of experience in data transformation/analysis in Python and SQL
-   4.5+ years of experience of artificial intelligence consultancy
-   10+ years of experience as project management/technical consultancy
-   Master of Data Science, UBC
-   Project Management Professional (PMP) certified since 2017

## RELEVANT PROFESSIONAL EXPERIENCE

### Wildlife Application Specialist (PC-02), CWS of ECCC, June 2023-Present

-   Support end-to-end data solutions by providing Python and SQL development for ETL-style data pipelines, PDF reporting, and automated data quality checks.  
    - Achievement: Increased automated data ingestion from 50% to over 70% (40% improvement) by experimenting different multi-stage name-matching strategies and choosing the best, greatly reducing manual effort and improving data timeliness.
-   Ensure timely releases (100% success rate) for the SAR-DMTS by leading UATs, collaborating with SMEs across departments, and resolving critical issues through bug fixes or workarounds, contributing to the administration of the SARA ([Species at risk public registry](https://www.canada.ca/en/environment-climate-change/services/species-risk-public-registry.html)).
-   Develop and enhance application modernization materials and documentation, clarifying business processes, data flows and system functionalities for internal stakeholders.


### Project Consultant of A.I. / Head of Sales, ClusterTech Limited, November 2016-June 2021

-   Drove the full customer lifecycle consultancy for data science projects, delivering solutions from pre-sales to delivery, resulting in enhanced client satisfaction.
-   Managed P&L of Sales with a focus on HPC and AI/ML/Analytics technologies, surpassing AI & Analytics targets in FY 2018-19 through strategic market segmentation and partnership development.
-   Secured lucrative contracts by crafting complex RFP responses in collaboration with the data science team and external partners.

### Regional Account Manager (Asia Pacific), The Collinson Group, November 2015-November 2016

-   Oversaw project implementation and product/market readiness for new deals, including digital lounge programs, maintaining 100% SLA compliance since Dec 2015 through proactive account servicing.

### Business Solutions Consultant, Business Markets, SmarTone Mobile Communications Limited, August 2013-November 2015

-   Led productization and implementation projects for B2B products and services, transitioning from initial qualification to market launch, covering areas such as cloud solutions and mobile app development.
-   Developed and implemented an ICT Training Program, boosting the department's ICT solution selling skills.
-   Conducted monthly ICT business reviews with senior management, utilizing tools like Cognos and MS Excel to inform strategic decisions.

## TECHNICAL SKILLS

-   Languages: Python (PyTorch, Pandas, Numpy, Geopandas), R, SQL, MongoDB, Stan
-   Microsoft 365 including MS Excel (VLOOKUP, Pivot Tables), Powerpoint, Word, Power BI and Access
-   APIs: REST APIs, JSON and XML
-   Project Management tools: Azure DevOps, GitHub, Trello, Microsoft Project
-   Data visualization: Altair, ggplot2, Dash, Plotly, Heroku, Shiny, Kepler.gl, MS Excel, Tableau, PowerBI
-   Platforms/Tools: Azure DevOps, AWS (S3, EMR, EC2), FME (Safe Software), docker, git, GitHub Actions (e.g. CI/CD), GNU make, PostgreSQL, MongoDB, Spark, Heroku, conda, VS Code, Jupyter, RStudio
-   Machine learning: classification, regression, linear models, decision tree, random forest, SVM, k-NN, clustering, natural language processing, ensemble methods, deep learning with neural networks (e.g. transformers (GPT), CNNs, Autoencoders, GANs)
-   Statistics & Probability: hypothesis testing, statistical inference, bootstrapping, simulations, experiment design (e.g. A/B testing)

## PUBLIC PRESENTATIONS

-   [ClusterTech Demonstrates How NLP Can Facilitate in Financial Industry](https://www.youtube.com/watch?v=o7gcxLfbv0Y), June 2020
-   [Using AI to Thrive in Challenging Times - ClusterTech X Pure Storage X NVIDIA Webinar](https://www.youtube.com/watch?v=HnlXPvLIXR0), November 2020

## RELEVANT EDUCATION

-   Master of Data Science, University of British Columbia September 2021-June 2022
    -   GPA = 93.3% (A+ equivalent)
    -   Relevant courses: Algorithms & Data Structures, Databases, Spatial & Time Series Analysis, Data Visualization, Automated Workflows, Machine Learning, NLP, Ethics (including EDI principles & bias prevention), Cloud Computing, Capstone Project
-   B.Sc. in Computer Science and Engineering, University of California, Los Angeles

## [DATA SCIENCE PROJECTS](stevenleung2018.github.io)

-   Public Service Data/AI Challenge (March 2025-ongoing): "Project Advisor: Risk and Requirements Applications"
    - Performed proof-of-concept experiments in code (Python/LangChain) to show that Retrieval-Augmented Generation (RAG) workflow with Large-language Models (LLMs) can be used to assist in the risk assessment and requirements gathering process for public service projects.
-   Capstone Project (May-Jun 2022): "Detection and Mitigation of Data Drift and Model Decay" for Goldspot Discoveries Corp.
    -   Engineered an adaptable Python framework that standardizes the monitoring and detection of data drift and model decay across various datasets and models, resulting in a scalable solution for ongoing data integrity.
    -   Utilized advanced tools and techniques such as PyTorch, Sci-kit Learn, Autoencoders, PCA, confidence distribution analysis, image property evaluation, and statistical tests to ensure robust performance.
-   Cloud Deployment of Machine Learning Model (Mar-Apr 2022): Deploying an API on AWS to predict daily rainfall in Sydney, Australia.
    -   Orchestrated the deployment of a machine learning model on AWS, leveraging EC2, S3, and EMR to process a large public dataset, enabling accurate daily rainfall predictions.
-   [DoggoDash](https://doggodash.onrender.com) (Feb-Mar 2022): An interactive dashboard for recommending dogs to potential owners.
    -   Created an engaging web application that recommends suitable dog breeds to prospective owners by analyzing user preferences, hosted on Heroku with dynamic visualizations powered by Plotly.
-   EDAhelper (Jan-Feb 2022): Open-source software packages in Python and R for simplifying Exploratory Data Analysis.
    -   Developed open-source software packages that transform complex Exploratory Data Analysis into one-line codes, streamlining the data exploration process for analysts.
-   Olympic Medals (Nov-Dec 2021): A reproducible data science report on the impact of age on winning medals
    -   Conducted a comprehensive study using reproducible data science techniques to test the hypothesis that age is a factor in winning Olympic medals, yielding insights into the correlation between age and athletic performance.

## VOLUNTEERING

-   Hackathon Mentor (2 cohorts), UBC Sauder School of Business, Feb 2024 and Feb 2025
    -   Mentored a student team as they prepared for their hackathon, simulating a real-world business scenario.
    - Acted as the team's simulated client, answering questions about business requirements and providing guidance.
    - Attended and evaluated data visualization presentations (e.g., Tableau dashboards) from all teams.
Provided constructive feedback on strengths and areas for improvement, simulating a real business setting.
-   Mentor for MDS students (2 cohorts), UBC, November 2023-April 2025
    -   Guided and supported two MDS students, providing strategic advice and fostering professional development to prepare them for successful careers post-graduation in June 2024.
-   Workshop on Project Management for MDS students, UBC, April 2024
    -   Delivered a workshop on project management best practices, sharing insights on effective project planning, execution, and monitoring to enhance students' understanding of project management principles.

## OTHER EDUCATION

-   Leading for Success 10-Day Consortium Program, Executive Education, Hong Kong University of Science and Technology 2015

## SPECIALIZED TRAINING / CERTIFICATIONS

-   Certified in Cybersecurity (CC) by ISC2 since December 2023
-   Azure Fundamentals (AZ-900) since May 2023
-   Project Management Professional (PMP) certified (Number: 2116816) since 2017
-   Introduction to Marketing (University of Pennsylvania), 2015
-   Effective Use of Microsoft Excel for Business Analysis, 2015
-   Architecting on AWS, Amazon Web Services, 2015

## LANGUAGES

-   Fluent in Chinese (Mandarin & Cantonese)
-   Professionally Proficient in written Japanese (JLPT N1)
