---
title: "How to set up and type French _occasionally_ on US English keyboards"
author: "Steven Leung"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary

-   In this file, I explain how to type French letters and punctuation on computers which are equipped with US English keyboards if you do this _occasionally_. I intend to either update this one or create a new one if I find a better way to do this for those who type French _often_. It is a work in progress. 

-   It is based on the fact that I am primarily an anglophone learning French. In order words, I will minimize the learning required to be able to type French. There is no need to learn any new keyboard layout (like `AZERTY` in France or `CSA` in Canada). The focus will be on how to type the "extra" French things that are not usually required when typing English.

-   I will cover both macOS, Windows, iPhone and iPad. This is applicable to computers sold to Canadian and US markets. I believe there are more markets using US English keyboards. If your keyboard layout is close to US English, it may be applicable to you too.

# Windows 11

## Setup

-   In addition to English, I would add French as an additional language. Since I am in Canada, I choose the region to be `Canada`. For the keyboard layout, I choose `US International`. 

## Typing 

### Accented letters

#### Accent aigu (e.g. `é`, `É`)

-   You would press `single quote`, release, and type the letter underneath the accent aigu. For instance, if you want to type `é` (the small letter `e` with accent aigu), it would be `single quote`, relese, then type `e`. If it is `É`, it would be `single quote` and `E`. (If Caps Lock is not already on, it would be `shift+e`.) Again, there are two keystrokes for one letter.
- Please see below if you need to type the single quote (which is the same character as the apostrophe).

#### Accent grave (e.g. `à`, `è`)
- You would type `backtick` where `backtick` stands for the key which is left to the number `1` on the keyboard which looks exactly like the accent grave itself, release, and then type the letter underneath the accent grave. For instance, if you want to type `à`, you would type `backtick`, release, then type `a`. 

#### Accent circonflexe (e.g. `î`)
- You would type `^` (or `shift+6`), release, and type the letter underneath the accent circonflexe. For instance, you would type `î` by `^`, release, then type `i`. 

#### Cédille (i.e. `ç`)
- `single quote`, release, then `c` (two keystrokes). 

#### Tréma (i.e. `ï`, `ü`)
- You would type `double quote` (or `shift+single quote`), release, and type the letter underneath the tréma. For instance, you would type `ï` by `double quote`, release, then type `i`.
- Please see below if you need to type the double quote.

#### Ligature (i.e. `œ`)
- For `œ`, hold the `alt` key, then type `0156` (4 digits), then release `alt`.
- For `Œ`, hold the `alt` key, then type `0140` (4 digits), then release `alt`.

### Punctuations

#### Guillemets (`«` and `»`, the double quotes that francophones use)
- `«` is `ctrl+alt+[` (one keystroke) or `right alt+[` (one keystroke)
- `»` is `ctrl+alt+]` (one keystroke) or `right alt+]` (one keystroke).

#### Apostrophe (`'` as in `J'ai`) which is the same character as the single quote.
- You would need to type the `single quote` followed by `space` (two keystrokes).

#### Double quote (`"`)
- You would need to type the `double quote` followed by `space` (two keystrokes).


# macOS Sonoma (14.5)

## Setup

-   It is the simplest. You just need to make sure that you have an input method as `English` and the keyboard layout is `US English`. The icon is a single capital letter `A`. This may already have been the default setting on your Mac. 


### Typing

### Accented letters

#### Accent aigu (e.g. `é`, `É`)

-   You would press `option+e`, release, and type the letter underneath the accent aigu. For instance, if you want to type `é` (the small letter `e` with accent aigu), it would be `option+e`, release, then type `e`. If it is `É`, it would be `option+e` and `E`. (If Caps Lock is not already on, it would be `shift+e`.) Again, there are two key strokes for one letter. 

#### Accent grave (e.g. `à`, `è`)
-   You would type `option+backtick` where `backtick` stands for the key which is left to the number `1` on the keyboard which looks exactly like the accent grave itself, release, and then type the letter underneath the accent grave. For instance, if you want to type `à`, you would type `option+backtick`, release, then type `a`. 

#### Accent circonflexe (e.g. `î`)
-   You would type `option+i`, release, and type the letter underneath the accent circonflexe. For instance, you would type `î` by `option+i`, release, then type `i`. 

#### Cédille (i.e. `ç`)
-   `option+c` (one keystroke). 

#### Tréma (i.e. `ï`, `ü`)
-   You would type `option+u`, release, and type the letter underneath the tréma. For instance, you would type `ï` by `option+u`, release, then type `i`. 

#### Ligature (i.e. `œ`)
- `option+q` (one keystroke)

### Punctuations

#### Guillemets (`«` and `»`, the double quotes that francophones use)
- `«` is `option+\` (one keystroke).
- `»` is `shift+option+\` (one keystroke).



# macOS (since Sonoma (14.5))

## Setup

-   It is the simplest. You just need to make sure that you have an input method as "English" and the keyboard layout is "US English". The icon is a single capital letter "A". This may already have been the default setting on your Mac. 


### Typing

### Accented letters

#### Accent aigu (e.g. `é`, `É`)

-   You would press `option+e`, release, and type the letter underneath the accent aigu. For instance, if you want to type `é` (the small letter `e` with accent aigu), it would be `option+e`, relese, then type `e`. If it is `É`, it would be `option+e` and `E`. (If Caps Lock is not already on, it would be `shift+e`.) Again, there are two key strokes for one letter. 

#### Accent grave (e.g. `à`, `è`)
-   You would type `option+backtick` where `backtick` stands for the key which is left to the number `1` on the keyboard which looks exactly like the accent grave itself, release, and then type the letter underneath the accent grave. For instance, if you want to type `à`, you would type `option+backtick`, release, then type `a`. 

#### Accent circonflexe (e.g. `î`)
-   You would type `option+i`, release, and type the letter underneath the accent circonflexe. For instance, you would type `î` by `option+i`, release, then type `i`. 

#### Cédille (i.e. `ç`)
-   `option+c` (one keystroke). 

#### Tréma (i.e. `ï`, `ü`)
-   You would type `option+u`, release, and type the letter underneath the tréma. For instance, you would type `ï` by `option+u`, release, then type `i`. 

#### Ligature (i.e. `œ`)
- `option+q` (one keystroke)

### Punctuations

#### Guillemets (`«` and `»`, the double quotes that francophones use)
- `«` is `option+\` (one keystroke).
- `»` is `shift+option+\` (one keystroke).



## iPhone and iPad

### Setup

#### Since iOS/iPadOS 18

- Apple has introduced the "bilingual" software keyboards, where English and French can coexist with one keyboard layout.  The spelling checks, autocomplete, etc. work at the same time without the need to switch between English and French.  If you don't like the keyboard layout to be bilingual, you can still use the old way of setting it up as in iOS/iPadOS 17 or earlier which I described below.
- `Settings` -> `General` -> `Keyboard` -> `Keyboards` -> `English` -> `Add Language...` -> `French (Canada)` (or any other variant of French you preferred)
- Now you should have both `English (Canada)` and `French (Canada)` under `Languages`.


#### iOS/iPadOS 17 (and perhaps earlier) 

- `Settings` -> `General` -> `Keyboard` -> `Keyboards` -> `Add New Keyboard`
- Type `French` and choose the variant of French you want (e.g. French (France), French (Canada)).  (Choosing a different variant here does not affect how you type.  It will affect the spell checking and autocomplete functionalities.)
- Choose one of those with `QWERTY`.


### Typing

- If you are lazy enough, you can try to type without worrying about the accented letters, and let auto-correction and spell checking do the work for you.  Roughly this works like 80% of the time.  For the rest, you would need to go back to the word to change the letters into the properly accented ones.  

#### Hardware keyboard
-   It would be exactly the same as you would do that on a Mac. Please refer to the section of Typing for macOS above. 

#### Software keyboard

##### Accented letters
- The general rule is that when you type, think of the closest letter, then hold on the letter until it pops up with more options.  Then different "variations" of the letter will be available to you.  For instance, if you want to type `é`, you would hold on `e` until it pops up with more options.  You will see that you can tap on `é` to choose it.  The same applies to holding on `c` for `ç`, `o` for `œ`.

##### Punctuations

###### Guillemets (`«` and `»`, the double quotes that francophones use)
- When you type the `double quote`, it will automatically convert it to the guillemets.  
- You don't have control over whether they will point to the left or right.  The device is supposed to figure it out for you automatically.

## References
1.  [Lawless French: Type Accents: Mac](https://www.lawlessfrench.com/faq/type-accents/type-accents-on-a-mac/)
2.  [Lawless French: Type Accents: Windows](https://www.lawlessfrench.com/faq/type-accents/type-accents-in-windows/)
3. [Lawless French: Type Accents: iPhone / iPad](https://www.lawlessfrench.com/faq/type-accents/type-accents-on-iphone-ipad/)
